/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_recorder_Mp3Encode */

#ifndef _Included_com_android_recorder_Mp3Encode
#define _Included_com_android_recorder_Mp3Encode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_recorder_Mp3Encode
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_recorder_Mp3Encode_close
  (JNIEnv *, jclass);

/*
 * Class:     com_android_recorder_Mp3Encode
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_android_recorder_Mp3Encode_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     com_android_recorder_Mp3Encode
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_android_recorder_Mp3Encode_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_android_recorder_Mp3Encode
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_android_recorder_Mp3Encode_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
